config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/index'

  Rails.application.routes.draw do
    devise_for :users, controllers: { sessions: 'users/sessions' }
    # get :users, to: 'users/sessions#index'
  end

  resources :participants
end

app/models/participant.rb
class Participant < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates_processing_of :avatar
  validate :avatar_size_validation

  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 2MB" if avatar.size > 2.megabytes
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    if current_user.admin?
      @participant.destroy
      respond_to do |format|
        format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to participants_url, notice: 'You don\'t have permission to destroy a participant.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(
        :firstname, :lastname, :birthdate, :nationality,
        :avatar, :avatar_cache, :remove_avatar
      )
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(participant) do |f| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, :start_year=>1900,:end_year=>2016 %>
  </div>

  <div class="field">
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </div>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
    <% if f.object.avatar? %>
      <%= image_tag f.object.avatar.thumb.url %>
      <%= f.label :remove_avatar %>
      <%= f.check_box :remove_avatar %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
 <div class="container">
   <h1>Editing Participant</h1>

   <%= render 'form', participant: @participant %>

   <% if current_user.admin? %>
     <%= link_to 'Destroy', @participant, method: :delete, data: { confirm: 'Are you sure?' } %> |
   <% end %>

   <%= link_to 'Show', @participant %> |
   <%= link_to 'Back', participants_path %>
 </div>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2 class="partitipants-title">Participants</h2>

  <%= link_to 'New Participant', new_participant_path %>

  <table class="form-table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Birthdate</th>
        <th>Nationality</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= participant.firstname %></td>
          <td><%= participant.lastname %></td>
          <td><%= participant.birthdate %></td>
          <td><%= participant.nationality %></td>
          <td><%= link_to 'Show', participant %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div class="container"><div class="container">

app/views/participants/new.html.erb
<div class="container">
  <h1>New Participant</h1>

  <%= render 'form', participant: @participant %>

  <%= link_to 'Back', participants_path %>
</div>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <p>
    <strong>Firstname:</strong>
    <%= @participant.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= @participant.lastname %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= @participant.birthdate %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= @participant.nationality %>
  </p>

  <p>
    <% if @participant.avatar? %>
    <strong>Avatar:</strong>
    <%= image_tag @participant.avatar.thumb.url %>
    <% end %>
  </p>

  <%= link_to 'Edit', edit_participant_path(@participant) %> |
  <%= link_to 'Back', participants_path %>
</div>